version: '3.9'
services:
  nginx:
    image: nginx:1.23-alpine
    volumes:
      - ./nginx:/nginx-conf
    working_dir: /nginx-conf
    command: nginx -c /nginx-conf/nginx.conf
    depends_on:
      - backend
    ports:
      - '5050:5050'
  backend:
    image: node:22-alpine
    volumes:
      - ./backend:/backend
    working_dir: /backend
    command: npm start
    entrypoint: /backend/entrypoint
    environment:
      - WISTIA_SUBDOMAIN=${WISTIA_SUBDOMAIN:-api.wistia.com}
      - SERVER_PORT=${SERVER_PORT:-5151}
      - WISTIA_PERMANENT_TOKEN
    extra_hosts:
      # Needed if pointing to localhost dev
      - api.wistia.io:host-gateway
  frontend:
    image: node:22-alpine
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    command: npm start
    entrypoint: /frontend/entrypoint
    environment:
      - REACT_APP_IFRAME_EMBED_URL=${REACT_APP_IFRAME_EMBED_URL:-https://fast.wistia.com}
      - REACT_APP_SERVER_ORIGIN=${REACT_APP_SERVER_ORIGIN:-http://localhost:5050}
      - PORT=5252
    extra_hosts:
      # Needed if pointing to localhost dev
      - api.wistia.io:host-gateway
  frontend-vanilla:
    image: nginx:1.23-alpine
    volumes:
      - ./frontend-vanilla:/nginx-conf
    working_dir: /nginx-conf
    command: nginx -c /nginx-conf/nginx.conf
    ports:
      - '8080:8080'
